name: Bug Report
description: File a bug report.
title: "[Bug] "
labels: ["bug"]
projects: ["Gold-Rush-Robotics/2"]
assignees:
  - dudebehinddude # assign it to PM to get a notif to sort/categorize it
body:
  - type: input
    id: what
    attributes:
      label: What is your issue?
      description: What is wrong
      placeholder: It's not working...
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How did it happen?
      description: What happened to make the issue appear? The more detailed your breakdown is the easier it is to reproduce/debug/fix
      placeholder: |
        1. Turned on robot
        2. Robot moved
        3. Error happened
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is it that this issue gets fixed? (Take your best guess)
      options:
        - High (blocking major development)
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: misc
    attributes:
      label: Other Information
      description: Attach other useful information (e.g., a video of what happened) here. The more info we have the easier it should be to fix.
      placeholder: "Here is a video of what is happening: (you can click here and drag and drop or paste to upload media)"
