#https://nodejs.org/en/about/previous-releases
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Yarn CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

defaults:
  run:
    working-directory: app

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: app/yarn.lock
      - run: yarn
      - run: yarn format:check
      - run: yarn build
      - run: yarn test
